include make.inc
# Group definitions

all: 
	+$(MAKE) -C src all
	+$(MAKE) -C fortranTesters all
	+$(MAKE) -C cTesters all

clean:
	+$(MAKE) -C src clean
	+$(MAKE) -C fortranTesters clean
	+$(MAKE) -C cTesters clean

